---

# disable login via ssh and ensure that connection is OK
- hosts: all
  become: true
  roles:
    - ssh

# setup base requirements
- hosts: all
  become: true
  roles:
    - base
    - apache
    - php
    - bind

# enable all the web-filled goodness
- hosts: all
  become: true
  roles:
    - website
    - vhosts



